### ISSUE TITLE
How to handle vertical and horizontal both like instagram?

### ISSUE THREAD

**Issue by Faiyyaz** [NehaKushwah993/InstagramVideoFeedClone#1]
Hi,

Thank you for such a great tool to handle exoplayer in Recyclerview. My issue is if we have a viewpager or horizontal recyclerview as a view type similar to instagram then how can we handle the video.

Please help me if possible.

Again thanks alot

**Comment by Faiyyazauxy** [comment]
Also it doesn't work when we use notifyItemChanged()

**Comment by rkoshti** [comment]
+1 @Faiyyaz looking same kind of behavior 

is there any update on this ?  @NehaKushwah993 How can we manage horizontal auto play videos in recycler view inside any of the child item in recycler view . Please do share if you above code can be useful in those scenarios

**Comment by rkoshti** [comment]
@NehaKushwah993 I am trying to update this repo in media3 exo player 

After update unable to get reference of videoComponent object  
![image](https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/19707208/dbd7a1aa-b67d-4b44-901b-b28338a57753)

Can you pls help to upgrade **InstaLikePlayerView** class in media3 exo player ? @NehaKushwah993

**Comment by Faiyyaz** [comment]
@rkoshti Try like this oldPlayer.player

**Comment by rkoshti** [comment]
![image](https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/19707208/d1b6a8b9-771d-473f-bbab-13971d3b2638)

@Faiyyaz tried but seems there is no player object can be obtained from oldPlayer instance

When i have seen the oldPlayer instance it is coming from this.player

and my import is **import androidx.media3.common.Player** for player instance 
Not sure whats wrong 

Can you share whole class file if you have also updated the same class @Faiyyaz

**Comment by Faiyyaz** [comment]
@rkoshti So that itself is the player object. I am not working on this library sorry I have moved to something else only.

**Comment by rkoshti** [comment]
@Faiyyaz No worries, I have tried that also

![image](https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/19707208/1a02cb77-9b5c-4f2e-ab10-8355daedd950)

After doing this it break's the whole player ... I am looking into it let's see where it goes

**Comment by Faiyyaz** [comment]
@rkoshti It seems clearVideoSurfaceView method is part of mediacontroller so maybe you need to get media controller of player for this one

**Comment by rkoshti** [comment]
@Faiyyaz I have tried but didn't found any method in player to obtainer media controller

will try more .....

**Comment by Faiyyaz** [comment]
I think you need to create mediasession. You can follow this sample

https://stackoverflow.com/questions/74035158/android-media3-session-controller-playback-not-starting

**Comment by rkoshti** [comment]
I think media3 session is required when we use service ..... I am trying to play videos in the recycler view 

In this example .... Neha has created a custom class **InstaLikePlayerView** which works fine with older exo player dependencies 

But when i have updated the exo dependencies it breaks video component ..... may be need dig some more to see how this can be done... @Faiyyaz 

Seems video component is deprecated....
https://developer.android.com/reference/androidx/media3/exoplayer/ExoPlayer.VideoComponent

**Comment by rkoshti** [comment]
Awaiting for @NehaKushwah993 's answer to see if she can help here in any case for acceleration

**Comment by NehaKushwah993** [comment]
Hello! 
Let me update the code.

Sorry for late reply..

**Comment by sagarishtech** [comment]
Hello @NehaKushwah993 for the great libs, I have implemented this in my project.

So as per above discussion I am using Latest exoplayer version in my App which is:
=> implementation 'com.google.android.exoplayer:exoplayer:2.19.1'

I solved everything in my project, but now problem is Videos is continuously playing in Loop, I spent 1.5 days but didn't find why it is happening, so I upgraded exoplayer version to Latest in your lib project with compileSdk & targetSdk 34, but I found same issue Videos is continuously playing in Loop, I don't know why, when I add Log statement inside InstaLikePlayerView class on onPlayerStateChanged() fun, it continuously gives 3 STATES : STATE_BUFFERING, STATE_READY, STATE_IDLE etc. lib is works with Older exoplayer version but not working in Latest exoplayer version.

So kindly update your lib project to Latest version. and try to solve our issue because I already spent so much time behind this. and I think this issue is nothing for you because you had made this great lib.

I am sharing 2 videos here 1 is my project's video & another is your project's video

=> My project's video
https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/94832544/ea61026e-dcef-4707-a9dc-d8f022269ed3

=> lib project's video
https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/94832544/5e11554f-59bf-478e-a485-f1d6de00e524

Waiting for your replay, please help all of us with this issue, Thank you so much.

**Comment by NehaKushwah993** [comment]
Sure, I will fix this by this weekend.

**Comment by sagarishtech** [comment]
> Sure, I will fix this by this weekend.

Thankyou for your Quick reply, Eagerly waiting for your NEW CODE, Thank you again

**Comment by NehaKushwah993** [comment]
Hello! Checkout latest code for playback and library updation from ExoPlayer2 to Media3 Exoplayer.
For precaching and horizontal pager video support you need to wait till next couple of weeks. Thanks

**Comment by NehaKushwah993** [comment]
> Hello @NehaKushwah993 for the great libs, I have implemented this in my project.
> 
> So as per above discussion I am using Latest exoplayer version in my App which is: => implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
> 
> I solved everything in my project, but now problem is Videos is continuously playing in Loop, I spent 1.5 days but didn't find why it is happening, so I upgraded exoplayer version to Latest in your lib project with compileSdk & targetSdk 34, but I found same issue Videos is continuously playing in Loop, I don't know why, when I add Log statement inside InstaLikePlayerView class on onPlayerStateChanged() fun, it continuously gives 3 STATES : STATE_BUFFERING, STATE_READY, STATE_IDLE etc. lib is works with Older exoplayer version but not working in Latest exoplayer version.
> 
> So kindly update your lib project to Latest version. and try to solve our issue because I already spent so much time behind this. and I think this issue is nothing for you because you had made this great lib.
> 
> I am sharing 2 videos here 1 is my project's video & another is your project's video
> 
> => My project's video https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/94832544/ea61026e-dcef-4707-a9dc-d8f022269ed3
> 
> => lib project's video https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/94832544/5e11554f-59bf-478e-a485-f1d6de00e524
> 
> Waiting for your replay, please help all of us with this issue, Thank you so much.

Try the latest code which is using ExoPlayer of media3. It supports caching but for precaching you need to wait till next week. Thanks!

**Comment by NehaKushwah993** [comment]
> ![image](https://private-user-images.githubusercontent.com/19707208/279911573-d1b6a8b9-771d-473f-bbab-13971d3b2638.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzU0MTksIm5iZiI6MTcwMjIzNTExOSwicGF0aCI6Ii8xOTcwNzIwOC8yNzk5MTE1NzMtZDFiNmE4YjktNzcxZC00NzNmLWJiYWItMTM5NzFkM2IyNjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDE5MDUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ODhiNjhmZjY5M2U3N2EzYjRiOTlhZWY3NDA5OGZjMWVjYjgxNDY2OWUyN2JmNzc4MWRiMzlkODUyNWQwNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WLnARauLh7ggCfBw_-XFrBXgdU7FSKsWiPkYd2CBi8Y)
> 
> @Faiyyaz tried but seems there is no player object can be obtained from oldPlayer instance
> 
> When i have seen the oldPlayer instance it is coming from this.player
> 
> and my import is **import androidx.media3.common.Player** for player instance Not sure whats wrong
> 
> Can you share whole class file if you have also updated the same class @Faiyyaz

Hi, Checkout latest code. Thanks

**Comment by sagarishtech** [comment]
> > Hello @NehaKushwah993 for the great libs, I have implemented this in my project.
> > So as per above discussion I am using Latest exoplayer version in my App which is: => implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
> > I solved everything in my project, but now problem is Videos is continuously playing in Loop, I spent 1.5 days but didn't find why it is happening, so I upgraded exoplayer version to Latest in your lib project with compileSdk & targetSdk 34, but I found same issue Videos is continuously playing in Loop, I don't know why, when I add Log statement inside InstaLikePlayerView class on onPlayerStateChanged() fun, it continuously gives 3 STATES : STATE_BUFFERING, STATE_READY, STATE_IDLE etc. lib is works with Older exoplayer version but not working in Latest exoplayer version.
> > So kindly update your lib project to Latest version. and try to solve our issue because I already spent so much time behind this. and I think this issue is nothing for you because you had made this great lib.
> > I am sharing 2 videos here 1 is my project's video & another is your project's video
> > => My project's video https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/94832544/ea61026e-dcef-4707-a9dc-d8f022269ed3
> > => lib project's video https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/94832544/5e11554f-59bf-478e-a485-f1d6de00e524
> > Waiting for your replay, please help all of us with this issue, Thank you so much.
> 
> Try the latest code which is using ExoPlayer of media3. It supports caching but for precaching you need to wait till next week. Thanks!

Thank you so much @NehaKushwah993 ji, for your great, quick work & efforts, I already have done with Latest version same as you done, I mean we both have done same code using Latest version, but I need Auto Play Videos, and its urgent requirements for my project so, but you have done by your side, although please you will try for Auto Play Videos as fast as possible, Again i'll eagerly waiting for your Next Auto play Videos update Thank you so much again.

**Comment by sagarishtech** [comment]
> > > Hello @NehaKushwah993 for the great libs, I have implemented this in my project.
> > > So as per above discussion I am using Latest exoplayer version in my App which is: => implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
> > > I solved everything in my project, but now problem is Videos is continuously playing in Loop, I spent 1.5 days but didn't find why it is happening, so I upgraded exoplayer version to Latest in your lib project with compileSdk & targetSdk 34, but I found same issue Videos is continuously playing in Loop, I don't know why, when I add Log statement inside InstaLikePlayerView class on onPlayerStateChanged() fun, it continuously gives 3 STATES : STATE_BUFFERING, STATE_READY, STATE_IDLE etc. lib is works with Older exoplayer version but not working in Latest exoplayer version.
> > > So kindly update your lib project to Latest version. and try to solve our issue because I already spent so much time behind this. and I think this issue is nothing for you because you had made this great lib.
> > > I am sharing 2 videos here 1 is my project's video & another is your project's video
> > > => My project's video https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/94832544/ea61026e-dcef-4707-a9dc-d8f022269ed3
> > > => lib project's video https://github.com/NehaKushwah993/InstagramVideoFeedClone/assets/94832544/5e11554f-59bf-478e-a485-f1d6de00e524
> > > Waiting for your replay, please help all of us with this issue, Thank you so much.
> > 
> > 
> > Try the latest code which is using ExoPlayer of media3. It supports caching but for precaching you need to wait till next week. Thanks!
> 
> Thank you so much @NehaKushwah993 ji, for your great, quick work & efforts, I already have done with Latest version same as you done, I mean we both have done same code using Latest version, but I need Auto Play Videos, and its urgent requirements for my project so, but you have done by your side, although please you will try for Auto Play Videos as fast as possible, Again i'll eagerly waiting for your Next Auto play Videos update Thank you so much again.

Oh sorry, I ran your project and after 30 minutes of searching why your videos is not Auto playing I found that reason at morning, your Firebase [Server URLs] Quota has been exceeded that's why video was not playing auto. So I replaced My URLs with yours, now its working Fine. thank you so much @NehaKushwah993 ji.

**Comment by NehaKushwah993** [comment]
Glad it worked! I will change the URLs to working ones.

**Comment by NehaKushwah993** [comment]
Hi, Checkout latest update for horizontal scrolling in main branch. 
Closing the ticket.
