### ISSUE TITLE
Error when scrolling to top from first element

### ISSUE THREAD

**Issue by nazirjonmakhmadkulov** [NehaKushwah993/InstagramVideoFeedClone#2]
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 26172 (RenderThread), pid 26144 (k.instagramfeed)

**Comment by nazirjonmakhmadkulov** [comment]
Bug fix
 android:hardwareAccelerated="false"

**Comment by NehaKushwah993** [comment]
Thanks! @nazirjonmakhmadkulov  nazirjonmakhmadkulov
