### ISSUE TITLE
Feature Request : Mute/Unmute button feature in feed list

### ISSUE THREAD

**Issue by rkoshti** [NehaKushwah993/InstagramVideoFeedClone#5]
How can we add a button in each item on bottom right corner for mute/unmute.... Tricky part will be in that will be like when you mute lets say from any of the position in adapter buttons in other positions should also react and updated automatically 

Do Let me know if it is feasible!!! @NehaKushwah993

**Comment by NehaKushwah993** [comment]
So in Instagram, when we mute any video then every video gets mute, and vice versa. I will add same functionality.

**Comment by NehaKushwah993** [comment]
https://github.com/NehaKushwah993/InstagramVideoFeedClone/pull/11 Done!
